<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Version>1.5.2</Version>
    <NoWarn>$(NoWarn);NU1902</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.44.0" />
  </ItemGroup>

  <Target Name="CopyPostTxt" AfterTargets="Build">
    <Copy SourceFiles="..\post.txt" DestinationFolder="$(OutputPath)" Condition="Exists('..\post.txt')" SkipUnchangedFiles="true" />
  </Target>

</Project>
